import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/themes/theme-provider"
import { Header } from "@/components/template/Header";
import { Footer } from "@/components/template/Footer";
import { GetAQuotePopup } from "@/components/template/GetAQuotePopup";
import icon from "@/assets/icon.png";
import { Toaster } from "@/components/ui/toast";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AD NextMatrix | Beyond Vision",
  description: "Generated by rohithreacts.dev",
  icons: {
    icon: icon.src,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning><ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <Header />
        <main className="flex-1">
          {children}
        </main>
        <Footer />
        <GetAQuotePopup />
        <Toaster />
      </ThemeProvider></body>
    </html>
  );
}
